# Generated by Django 3.2.13 on 2022-05-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsonzambia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfeature',
            name='ft_town',
            field=models.CharField(default=' ', max_length=100, verbose_name='Town/City'),
            preserve_default=False,
        ),
    ]
