# Generated by Django 4.0.5 on 2022-06-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsonzambia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='postfeature',
            name='ft_views',
            field=models.ManyToManyField(blank=True, related_name='feature_view', to='whatsonzambia.ipmodel'),
        ),
    ]
