# Generated by Django 4.0.5 on 2022-06-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsonzambia', '0002_ipmodel_postfeature_ft_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='whatsonzambia.ipmodel'),
        ),
        migrations.AlterField(
            model_name='postfeature',
            name='ft_views',
            field=models.ManyToManyField(blank=True, related_name='feature_views', to='whatsonzambia.ipmodel'),
        ),
    ]
